create table if not exists users (
  id integer generated by default as identity primary key,
  user_id varchar(50) unique,
  username varchar(100) not null unique,
  email varchar(255) not null unique,
  hashed_password varchar(255) not null,
  role varchar(50) not null,
  is_approved integer not null default 0,
  password_reset_requested integer not null default 0,
  created_at text not null,
  oauth_provider varchar(50),
  oauth_sub varchar(255),
  profile_pic text
);

create table if not exists events (
  id integer generated by default as identity primary key,
  event_name varchar(150) not null unique,
  created_at text not null,
  created_by varchar(100) not null,
  updated_at text,
  updated_by varchar(100)
);

create table if not exists agencies (
  id integer generated by default as identity primary key,
  name varchar(150) not null unique,
  address varchar(255),
  phone varchar(50),
  fax varchar(50),
  email varchar(255),
  created_at text not null,
  created_by varchar(100) not null,
  updated_at text,
  updated_by varchar(100)
);

create table if not exists agency_suboptions (
  id integer generated by default as identity primary key,
  name varchar(150) not null,
  agency_id integer,
  created_at text not null,
  created_by varchar(100) not null,
  updated_at text,
  updated_by varchar(100)
);

create table if not exists ccus (
  id integer generated by default as identity primary key,
  name varchar(150) not null unique,
  address varchar(255),
  street varchar(255),
  city varchar(100),
  state varchar(20),
  zip_code varchar(20),
  phone varchar(50),
  fax varchar(50),
  email varchar(255),
  care_coordinator_name varchar(150),
  created_at text not null,
  created_by varchar(100) not null,
  updated_at text,
  updated_by varchar(100)
);

create table if not exists mcos (
  id integer generated by default as identity primary key,
  name varchar(150) not null unique,
  created_at text not null,
  created_by varchar(100) not null,
  updated_at text,
  updated_by varchar(100)
);

create table if not exists leads (
  id integer generated by default as identity primary key,
  created_at text not null,
  updated_at text not null,
  created_by varchar(100),
  updated_by varchar(100),
  owner_id integer,
  staff_name varchar(150) not null,
  first_name varchar(150) not null,
  last_name varchar(150) not null,
  source varchar(150) not null,
  event_name varchar(150),
  word_of_mouth_type varchar(50),
  other_source_type varchar(150),
  active_client integer not null default 0,
  referral_type varchar(50),
  agency_id integer,
  agency_suboption_id integer,
  ccu_id integer,
  mco_id integer,
  authorization_received integer not null default 0,
  care_status varchar(50),
  priority varchar(50),
  call_status_updated_by varchar(100),
  call_status_updated_at text,
  tag_color varchar(30),
  soc_date text,
  phone varchar(50) not null,
  street varchar(255),
  city varchar(100),
  zip_code varchar(20),
  dob text,
  age integer,
  gender varchar(30),
  medicaid_no varchar(100),
  e_contact_name varchar(150),
  e_contact_relation varchar(100),
  e_contact_phone varchar(50),
  last_contact_status varchar(50) not null,
  last_contact_date text,
  comments text,
  ssn varchar(50),
  email varchar(255),
  custom_user_id varchar(50),
  relation_to_client varchar(100),
  medicaid_status varchar(10),
  address text,
  state varchar(20),
  deleted_at text,
  deleted_by varchar(100),
  send_reminders integer not null default 1,
  caregiver_type varchar(50),
  referral_sent_date text
);

create table if not exists activity_logs (
  id integer generated by default as identity primary key,
  timestamp text not null,
  user_id integer,
  username varchar(100) not null,
  action_type varchar(50) not null,
  entity_type varchar(50) not null,
  entity_id integer,
  entity_name varchar(200),
  description text not null,
  old_value text,
  new_value text,
  keywords varchar(200),
  ip_address varchar(50)
);

create table if not exists lead_comments (
  id integer generated by default as identity primary key,
  lead_id integer not null,
  username varchar(100) not null,
  content text not null,
  created_at text not null
);

create table if not exists attachments (
  id integer generated by default as identity primary key,
  lead_id integer not null,
  filename varchar(255) not null,
  file_path varchar(500) not null,
  file_size integer not null,
  uploaded_by varchar(100) not null,
  uploaded_at text not null
);

create table if not exists email_reminders (
  id integer generated by default as identity primary key,
  lead_id integer not null,
  recipient_email varchar(255) not null,
  subject varchar(255) not null,
  sent_at text not null,
  sent_by varchar(100) not null,
  status varchar(50) not null,
  error_message text,
  lead_name varchar(300) not null,
  lead_status varchar(50) not null,
  lead_source varchar(150) not null
);

create table if not exists email_templates (
  id integer generated by default as identity primary key,
  slug varchar(100) not null unique,
  subject varchar(255) not null,
  body text not null,
  updated_at text not null
);

create table if not exists session_tokens (
  id integer generated by default as identity primary key,
  token varchar(255) not null unique,
  user_id integer not null,
  created_at text not null,
  expires_at text not null
);

create table if not exists magic_link_tokens (
  id integer generated by default as identity primary key,
  token varchar(255) not null unique,
  email varchar(255) not null,
  created_at text not null,
  expires_at text not null,
  is_used integer not null default 0
);

create table if not exists notifications (
  id integer generated by default as identity primary key,
  user_id integer not null,
  title varchar(255) not null,
  description text not null,
  entity_id integer,
  entity_type varchar(50),
  is_read integer not null default 0,
  created_at text not null
);

create table if not exists notification_reads (
  user_id integer not null,
  notification_id text not null,
  read_at text not null,
  primary key (user_id, notification_id)
);

do $$
declare
  column_row record;
begin
  for column_row in
    select table_schema, table_name, column_name
    from information_schema.columns
    where table_schema = 'public'
      and table_name in (
        'users',
        'events',
        'agencies',
        'agency_suboptions',
        'ccus',
        'mcos',
        'leads',
        'activity_logs',
        'lead_comments',
        'attachments',
        'email_reminders',
        'email_templates',
        'session_tokens',
        'magic_link_tokens',
        'notifications',
        'notification_reads'
      )
      and data_type = 'character varying'
  loop
    execute format(
      'alter table %I.%I alter column %I type text',
      column_row.table_schema,
      column_row.table_name,
      column_row.column_name
    );
  end loop;
end $$;

create index if not exists idx_leads_owner_id on leads(owner_id);
create index if not exists idx_leads_staff_name on leads(staff_name);
create index if not exists idx_leads_active_client on leads(active_client);
create index if not exists idx_leads_last_contact_status on leads(last_contact_status);
create index if not exists idx_leads_priority on leads(priority);
create index if not exists idx_leads_deleted_at on leads(deleted_at);
create index if not exists idx_leads_source on leads(source);
create index if not exists idx_leads_created_at on leads(created_at desc);
create index if not exists idx_activity_logs_timestamp on activity_logs(timestamp);
create index if not exists idx_activity_logs_username on activity_logs(username);
create index if not exists idx_lead_comments_lead_id on lead_comments(lead_id);
create index if not exists idx_attachments_lead_id on attachments(lead_id);
create index if not exists idx_notification_reads_user_id on notification_reads(user_id);

alter table users alter column is_approved drop default;
alter table users alter column password_reset_requested drop default;
alter table leads alter column active_client drop default;
alter table leads alter column authorization_received drop default;
alter table leads alter column send_reminders drop default;
alter table magic_link_tokens alter column is_used drop default;
alter table notifications alter column is_read drop default;

alter table users alter column is_approved type integer using case when is_approved::text in ('true','1') then 1 else 0 end;
alter table users alter column password_reset_requested type integer using case when password_reset_requested::text in ('true','1') then 1 else 0 end;
alter table leads alter column active_client type integer using case when active_client::text in ('true','1') then 1 else 0 end;
alter table leads alter column authorization_received type integer using case when authorization_received::text in ('true','1') then 1 else 0 end;
alter table leads alter column send_reminders type integer using case when send_reminders::text in ('true','1') then 1 else 0 end;
alter table magic_link_tokens alter column is_used type integer using case when is_used::text in ('true','1') then 1 else 0 end;
alter table notifications alter column is_read type integer using case when is_read::text in ('true','1') then 1 else 0 end;

alter table users alter column is_approved set default 0;
alter table users alter column password_reset_requested set default 0;
alter table leads alter column active_client set default 0;
alter table leads alter column authorization_received set default 0;
alter table leads alter column send_reminders set default 1;
alter table magic_link_tokens alter column is_used set default 0;
alter table notifications alter column is_read set default 0;
