import express from "express";
import cors from "cors";
import path from "path";
import fs from "fs";
import crypto from "crypto";
import jwt from "jsonwebtoken";
import multer from "multer";
import ExcelJS from "exceljs";
import { AlignmentType, Document, PageOrientation, Packer, Paragraph, Table, TableCell, TableLayoutType, TableRow, TextRun, WidthType } from "docx";
import { fileURLToPath } from "url";
import { createDatabase } from "./db.js";
import { searchSuggestionRelevance } from "./suggestionRank.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..", "..");
const dbPath = process.env.LEAD_DB || path.join(rootDir, "backend", "leads.db");
const uploadsDir = path.join(rootDir, "backend", "uploads");
const legacyUploadDirs = [
  uploadsDir,
  path.join(rootDir, "uploads"),
  path.join(rootDir, "rebuild frontend", "backend", "uploads"),
  path.join(rootDir, "rebuild frontend", "uploads")
];
const distDir = path.resolve(__dirname, "..", "dist");
const schemaPath = path.resolve(__dirname, "..", "migrations", "aws", "postgres-schema.sql");
const jwtSecret = process.env.JWT_SECRET_KEY || "f2f9c7c55bdbe69ea5ac0da9b29fb2c26555a720266bfb4ba936568b27ab7cef";
const externalLeadApiKey = process.env.LEAD_MANAGER_API_KEY;
fs.mkdirSync(uploadsDir, { recursive: true });

const db = await createDatabase({ dbPath, schemaPath });
if (db.mode === "sqlite") {
  db.exec(`create table if not exists notification_reads (
    user_id integer not null,
    notification_id text not null,
    read_at text not null,
    primary key (user_id, notification_id)
  )`);
  const leadColumns = db.columns("leads");
  if (leadColumns.length && !leadColumns.includes("gender")) {
    db.exec("alter table leads add column gender varchar(30)");
  }
  if (leadColumns.length && !leadColumns.includes("is_chicago_referral")) {
    db.exec("alter table leads add column is_chicago_referral integer not null default 0");
  }
}

const app = express();
const upload = multer({ dest: uploadsDir });
app.use(cors({ origin: true, credentials: true }));
app.use(express.json({ limit: "10mb" }));
app.use((req, res, next) => {
  if (req.path.startsWith("/api/")) {
    res.setHeader("Cache-Control", "no-store, no-cache, must-revalidate, proxy-revalidate");
    res.setHeader("Pragma", "no-cache");
    res.setHeader("Expires", "0");
  }
  next();
});

const now = () => new Date().toISOString().replace("T", " ").replace("Z", "");
const bool = (v) => (v ? 1 : 0);
const defaultLeadSources = ["Home Health Notify", "Web", "Direct Through CCU", "Event", "Word of Mouth", "Transfer", "Other"];
const publicUser = (u, options = {}) => u && ({
  id: u.id,
  user_id: u.user_id,
  username: u.username,
  email: u.email,
  role: u.role,
  is_approved: !!u.is_approved,
  ...(options.profile ? { profile_pic: u.profile_pic } : {})
});
const normalizePhone = (value = "") => String(value || "").replace(/\D/g, "");

const cache = new Map();
function cacheKey(name, parts = []) {
  return [name, ...parts.map((part) => String(part ?? ""))].join(":");
}

async function cached(key, ttlMs, loader) {
  const hit = cache.get(key);
  if (hit && hit.expires > Date.now()) return hit.value;
  const value = await loader();
  cache.set(key, { value, expires: Date.now() + ttlMs });
  return value;
}

function clearDataCaches() {
  cache.clear();
}

async function ensureLeadSources() {
  if (db.mode === "sqlite") {
    await db.run(`create table if not exists lead_sources (
      id integer primary key autoincrement,
      name varchar(150) not null unique,
      created_at text not null,
      created_by varchar(100) not null,
      updated_at text,
      updated_by varchar(100)
    )`);
  } else {
    await db.run(`create table if not exists lead_sources (
      id integer generated by default as identity primary key,
      name varchar(150) not null unique,
      created_at text not null,
      created_by varchar(100) not null,
      updated_at text,
      updated_by varchar(100)
    )`);
  }
  const count = await db.get("select count(*) as count from lead_sources");
  if (Number(count?.count || 0) === 0) {
    for (const source of defaultLeadSources) {
      await db.run("insert into lead_sources (name,created_at,created_by) values (?,?,?)", source, now(), "system");
    }
  }
}

function uniquePaths(paths) {
  return [...new Set(paths.filter(Boolean).map((item) => path.resolve(item)))];
}

function resolveAttachmentPath(att) {
  if (!att) return null;
  const savedPath = String(att.file_path || "");
  const savedName = path.basename(savedPath);
  const safeStoredName = savedName && savedName !== "." ? savedName : "";
  const currentUploadName = att.lead_id && att.filename ? `${att.lead_id}_${att.filename}` : "";
  const candidates = [];

  if (savedPath) {
    candidates.push(savedPath);
    if (!path.isAbsolute(savedPath)) {
      candidates.push(path.join(rootDir, savedPath));
      candidates.push(path.join(uploadsDir, savedPath));
    }
  }

  for (const dir of legacyUploadDirs) {
    if (safeStoredName) candidates.push(path.join(dir, safeStoredName));
    if (currentUploadName) candidates.push(path.join(dir, currentUploadName));
    if (att.filename) candidates.push(path.join(dir, att.filename));
  }

  return uniquePaths(candidates).find((candidate) => fs.existsSync(candidate)) || null;
}

const originalDbRun = db.run.bind(db);
db.run = async (...args) => {
  const result = await originalDbRun(...args);
  clearDataCaches();
  return result;
};
await ensureLeadSources();

function duplicateKind(lead) {
  if (!lead) return "";
  if (Number(lead.authorization_received) === 1) return lead.source === "Transfer" && lead.care_status !== "Care Start" ? "transfer case" : "authorization";
  if (Number(lead.active_client) === 1) return "referral";
  return "lead";
}

function searchTargetForLead(lead) {
  const folderQuery = Number(lead.is_chicago_referral) === 1 ? "active=Chicago&" : "";
  if (Number(lead.authorization_received) === 1) {
    if (lead.source === "Transfer" && lead.care_status !== "Care Start") return { targetPage: "Transfer Cases", targetUrl: `/authorizations?${folderQuery}idSearch=${lead.id}&transferView=true` };
    return { targetPage: "Authorizations", targetUrl: `/authorizations?${folderQuery}idSearch=${lead.id}` };
  }
  if (Number(lead.active_client) === 1) return { targetPage: "Referrals Sent", targetUrl: `/referrals?${folderQuery}idSearch=${lead.id}` };
  return { targetPage: "View Leads", targetUrl: `/view-leads?${folderQuery}idSearch=${lead.id}` };
}

const notificationFieldLabels = {
  active_client: "Referral Status",
  agency_id: "Payor",
  authorization_received: "Authorization",
  care_status: "Care Status",
  caregiver_type: "Caregiver Type",
  ccu_id: "CCU",
  is_chicago_referral: "Chicago Referral",
  last_contact_status: "Contact Status",
  priority: "Priority",
  referral_sent_date: "Referral Sent Date",
  referral_type: "Referral Type",
  send_reminders: "Reminders",
  soc_date: "SOC Date",
  staff_name: "Staff"
};

const notificationIgnoredFields = new Set([
  "id",
  "created_at",
  "updated_at",
  "created_by",
  "updated_by",
  "deleted_at",
  "deleted_by",
  "call_status_updated_at",
  "agency_address",
  "agency_email",
  "agency_fax",
  "agency_phone",
  "ccu_care_coordinator_name",
  "ccu_city",
  "ccu_email",
  "ccu_fax",
  "ccu_phone",
  "ccu_state",
  "ccu_street",
  "ccu_zip_code"
]);

function titleCase(value) {
  return String(value || "")
    .replace(/_/g, " ")
    .toLowerCase()
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function parseJsonMaybe(value) {
  if (!value) return null;
  if (typeof value === "object") return value;
  try {
    return JSON.parse(value);
  } catch {
    return null;
  }
}

function cleanNotificationValue(value) {
  if (value === undefined || value === null || value === "") return "Not added";
  if (typeof value === "boolean") return value ? "Yes" : "No";
  if (value === 1 || value === "1") return "Yes";
  if (value === 0 || value === "0") return "No";
  return String(value);
}

function notificationValueFor(field, data) {
  if (!data) return "Not added";
  if (field === "agency_id") return cleanNotificationValue(data.agency_name || data.agency_id);
  if (field === "ccu_id") return cleanNotificationValue(data.ccu_name || data.ccu_id);
  if (field === "active_client") return Number(data.active_client) === 1 ? "Referral" : "Lead";
  if (field === "authorization_received") return Number(data.authorization_received) === 1 ? "Received" : "Pending";
  if (field === "is_chicago_referral") return Number(data.is_chicago_referral) === 1 ? "Yes" : "No";
  return cleanNotificationValue(data[field]);
}

function changedNotificationFields(oldValue, newValue) {
  const oldData = parseJsonMaybe(oldValue);
  const newData = parseJsonMaybe(newValue);
  if (!oldData || !newData) return [];

  const keys = new Set([...Object.keys(oldData), ...Object.keys(newData)]);
  return [...keys]
    .filter((key) => !notificationIgnoredFields.has(key))
    .map((key) => ({
      key,
      label: notificationFieldLabels[key] || titleCase(key),
      before: notificationValueFor(key, oldData),
      after: notificationValueFor(key, newData)
    }))
    .filter((change) => change.before !== change.after);
}

function activityNotificationMessage(activity) {
  const changes = changedNotificationFields(activity.old_value, activity.new_value);
  const actor = activity.username || "Someone";
  const subject = activity.entity_name || "this record";
  if (changes.length === 1) {
    const change = changes[0];
    const prefix = Number(activity.lead_active_client) === 1 ? "Referral Updated" : "Lead Updated";
    return `${prefix}: ${change.label} changed from "${change.before}" to "${change.after}" by ${actor}.`;
  }
  if (changes.length > 1) {
    const labels = changes.slice(0, 3).map((change) => change.label).join(", ");
    const prefix = Number(activity.lead_active_client) === 1 ? "Referral Updated" : "Lead Updated";
    return `${prefix}: ${actor} updated ${changes.length} fields for ${subject}: ${labels}${changes.length > 3 ? ", ..." : ""}.`;
  }
  return activity.description || activity.action_type || "Recent activity";
}

function reminderNotificationMessage(lead) {
  if (Number(lead.active_client) !== 1) {
    return `Lead Follow-up: Current status is "${lead.last_contact_status || "Not added"}".${lead.phone ? ` Phone: ${lead.phone}` : ""}`;
  }
  if (Number(lead.authorization_received) === 1 && lead.care_status !== "Care Start") {
    return `Care Start Follow-up: Authorization received. Current care status: ${lead.care_status || "Not Start"}.${lead.phone ? ` Phone: ${lead.phone}` : ""}`;
  }
  return `Referral Follow-up: Current status is "${lead.last_contact_status || "Not added"}". Type: ${lead.referral_type || "Regular"}.${lead.phone ? ` Phone: ${lead.phone}` : ""}`;
}

async function findDuplicateLead(body) {
  const firstName = String(body.first_name || "").trim().toLowerCase();
  const lastName = String(body.last_name || "").trim().toLowerCase();
  const phone = normalizePhone(body.phone);
  if (!firstName || !lastName || !phone) return null;
  const candidates = await db.all("select * from leads where lower(first_name)=@firstName and lower(last_name)=@lastName", { firstName, lastName });
  return candidates.find((lead) => normalizePhone(lead.phone) === phone) || null;
}

function b64DecodePasslib(value) {
  let text = value.replace(/\./g, "+");
  while (text.length % 4) text += "=";
  return Buffer.from(text, "base64");
}

function verifyPassword(password, stored) {
  if (!stored) return false;
  if (stored.startsWith("$pbkdf2-sha256$")) {
    const [, , rounds, salt, digest] = stored.split("$");
    const key = crypto.pbkdf2Sync(Buffer.from(password, "utf8").subarray(0, 72), b64DecodePasslib(salt), Number(rounds), 32, "sha256");
    return crypto.timingSafeEqual(key, b64DecodePasslib(digest));
  }
  if (!stored.startsWith("$")) return stored === password;
  return false;
}

function passlibB64(buffer) {
  return Buffer.from(buffer).toString("base64").replace(/\+/g, ".").replace(/=+$/g, "");
}

function hashPassword(password) {
  const rounds = 29000;
  const salt = crypto.randomBytes(16);
  const key = crypto.pbkdf2Sync(Buffer.from(password, "utf8").subarray(0, 72), salt, rounds, 32, "sha256");
  return `$pbkdf2-sha256$${rounds}$${passlibB64(salt)}$${passlibB64(key)}`;
}

async function auth(req, res, next) {
  const header = req.headers.authorization || "";
  const tokenFromHeader = header.startsWith("Bearer ") ? header.slice(7) : null;
  const tokenFromQuery = typeof req.query.token === "string" ? req.query.token : null;
  const token = tokenFromHeader || tokenFromQuery;
  if (!token) return res.status(401).json({ error: "Missing token" });
  try {
    const payload = jwt.verify(token, jwtSecret);
    const currentUser = await db.get("select id,user_id,username,role,is_approved from users where id = ?", payload.user_id || payload.sub);
    if (!currentUser || !currentUser.is_approved) return res.status(401).json({ error: "Invalid user" });
    req.user = {
      ...payload,
      sub: currentUser.username,
      username: currentUser.username,
      role: currentUser.role,
      user_id: currentUser.id,
      employee_id: currentUser.user_id
    };
    next();
  } catch {
    res.status(401).json({ error: "Invalid token" });
  }
}

function isAdminRole(role) {
  return role === "admin" || role === "super_admin";
}

function isSuperAdminRole(role) {
  return role === "super_admin";
}

function admin(req, res, next) {
  if (!isAdminRole(req.user.role)) return res.status(403).json({ error: "Admin only" });
  next();
}

function superAdmin(req, res, next) {
  if (!isSuperAdminRole(req.user.role)) return res.status(403).json({ error: "Super admin only" });
  next();
}

async function logActivity(user, actionType, entityType, entityId, entityName, description, oldValue = null, newValue = null, keywords = "") {
  await db.run(`insert into activity_logs (timestamp,user_id,username,action_type,entity_type,entity_id,entity_name,description,old_value,new_value,keywords)
    values (@timestamp,@user_id,@username,@action_type,@entity_type,@entity_id,@entity_name,@description,@old_value,@new_value,@keywords)`, {
    timestamp: now(),
    user_id: user?.user_id || user?.id || null,
    username: user?.username || "system",
    action_type: actionType,
    entity_type: entityType,
    entity_id: entityId,
    entity_name: entityName,
    description,
    old_value: oldValue ? JSON.stringify(oldValue) : null,
    new_value: newValue ? JSON.stringify(newValue) : null,
    keywords
  });
}

const leadSelect = `select leads.*, agencies.name as agency_name, agencies.address as agency_address, agencies.phone as agency_phone,
  agencies.fax as agency_fax, agencies.email as agency_email, ccus.name as ccu_name, ccus.street as ccu_street,
  ccus.city as ccu_city, ccus.state as ccu_state, ccus.zip_code as ccu_zip_code, ccus.phone as ccu_phone,
  ccus.fax as ccu_fax, ccus.email as ccu_email, ccus.care_coordinator_name as ccu_care_coordinator_name
  from leads left join agencies on agencies.id = leads.agency_id left join ccus on ccus.id = leads.ccu_id`;
const leadWriteFields = new Set([
  "owner_id","staff_name","first_name","last_name","source","event_name","word_of_mouth_type","other_source_type",
  "active_client","referral_type","agency_id","agency_suboption_id","ccu_id","authorization_received","care_status","priority",
  "tag_color","soc_date","phone","street","city","zip_code","dob","age","gender","medicaid_no","e_contact_name",
  "e_contact_relation","e_contact_phone","last_contact_status","comments","ssn","email","custom_user_id","state",
  "send_reminders","caregiver_type","referral_sent_date","deleted_at","deleted_by","call_status_updated_by","call_status_updated_at",
  "is_chicago_referral"
]);

function buildLeadQuery(q = {}, user) {
  const where = [];
  const params = {};
  const includeDeleted = q.includeDeleted === "true" || q.includeDeleted === true;
  if (includeDeleted) where.push("leads.deleted_at is not null");
  else where.push("leads.deleted_at is null");

  if (q.onlyMine === "true" || q.onlyMine === true) {
    where.push("(leads.owner_id = @ownerId or leads.staff_name = @staffName)");
    params.ownerId = user.user_id;
    params.staffName = user.username;
  }
  if (q.type === "lead") {
    where.push("coalesce(leads.active_client,0) = 0");
  }
  if (q.type === "referral") {
    where.push("leads.active_client = 1");
    where.push("coalesce(leads.authorization_received,0) = 0");
  }
  if (q.type === "authorization") {
    where.push("leads.active_client = 1");
    where.push("leads.authorization_received = 1");
    if (q.transferView === "true" || q.transferView === true) {
      where.push("leads.source = 'Transfer'");
      where.push("coalesce(leads.care_status,'') != 'Care Start'");
    } else {
      where.push("(leads.source != 'Transfer' or leads.care_status = 'Care Start')");
    }
  }
  if (q.active === "Chicago") {
    where.push("coalesce(leads.is_chicago_referral,0) = 1");
  } else if (q.active !== "All") {
    where.push("coalesce(leads.is_chicago_referral,0) = 0");
  }
  if (q.active && q.active !== "All") {
    if (q.active === "Chicago") {
      // Chicago Referral is its own folder. Keep original workflow status untouched.
    } else {
    const statusSets = {
      lead: {
        column: "last_contact_status",
        active: ["Initial Call", "No Response"]
      },
      referral: {
        column: "last_contact_status",
        active: ["Initial Referral Sent", "Assessment Scheduled", "Assessment Done"]
      },
      authorization: {
        column: "care_status",
        active: ["Care Start", "Not Start", "Transfer", "Transfer Received"]
      }
    };
    const config = statusSets[q.type] || statusSets.lead;
    const list = config.active;
    const columnSql = q.type === "lead"
      ? "case when trim(coalesce(leads.care_status,'')) != '' then leads.care_status else leads.last_contact_status end"
      : config.column === "care_status"
        ? "leads.care_status"
        : "leads.last_contact_status";
    const activeSql = `${columnSql} in (${list.map((_, i) => `@active${i}`).join(",")})`;
    if (q.active === "Active") where.push(activeSql);
    else where.push(`(${columnSql} is null or trim(${columnSql}) = '' or ${columnSql} not in (${list.map((_, i) => `@active${i}`).join(",")}))`);
    list.forEach((v, i) => { params[`active${i}`] = v; });
    }
  }
  if (q.status && q.status !== "All") {
    where.push("(leads.last_contact_status = @status or leads.care_status = @status)");
    params.status = q.status;
  }
  if (q.callStatus && q.callStatus !== "All") {
    where.push("coalesce(leads.priority,'Not Called') = @callStatus");
    params.callStatus = q.callStatus;
  }
  if (q.referralType && q.referralType !== "All") {
    where.push("coalesce(leads.referral_type,'Regular') = @referralType");
    params.referralType = q.referralType;
  }
  if (q.tagColor && q.tagColor !== "All") {
    where.push("leads.tag_color = @tagColor");
    params.tagColor = q.tagColor;
  }
  if (q.caregiverType && q.caregiverType !== "All") {
    where.push("leads.caregiver_type = @caregiverType");
    params.caregiverType = q.caregiverType;
  }
  if (q.ccu && q.ccu !== "All") {
    where.push("ccus.name = @ccu");
    params.ccu = q.ccu;
  }
  if (q.payor && q.payor !== "All") {
    where.push("agencies.name = @payor");
    params.payor = q.payor;
  }
  if (q.staff) {
    where.push("lower(leads.staff_name) like @staff");
    params.staff = `%${String(q.staff).toLowerCase()}%`;
  }
  if (q.source) {
    where.push("lower(leads.source) like @source");
    params.source = `%${String(q.source).toLowerCase()}%`;
  }
  if (q.search) {
    const tokens = String(q.search).trim().toLowerCase().split(/\s+/).filter(Boolean);
    tokens.forEach((token, i) => {
      params[`search${i}`] = `%${token}%`;
      if (q.pageSearch === "true" || q.pageSearch === true) {
        where.push(`(lower(leads.first_name) like @search${i} or lower(leads.last_name) like @search${i} or lower(leads.first_name || ' ' || leads.last_name) like @search${i} or lower(leads.last_name || ' ' || leads.first_name) like @search${i})`);
      } else {
        where.push(`(lower(leads.first_name) like @search${i} or lower(leads.last_name) like @search${i} or lower(leads.first_name || ' ' || leads.last_name) like @search${i} or lower(leads.last_name || ' ' || leads.first_name) like @search${i} or lower(coalesce(leads.phone,'')) like @search${i} or lower(coalesce(leads.medicaid_no,'')) like @search${i} or lower(coalesce(leads.custom_user_id,'')) like @search${i} or cast(leads.id as text) like @search${i})`);
      }
    });
  }
  if (q.idSearch) {
    if (q.pageSearch === "true" || q.pageSearch === true) {
      where.push("cast(leads.id as text) = @idSearch");
      params.idSearch = String(q.idSearch).trim();
    } else {
      where.push("cast(leads.id as text) like @idSearch");
      params.idSearch = `%${q.idSearch}%`;
    }
  }
  if (q.startDate) {
    where.push("date(leads.created_at) >= date(@startDate)");
    params.startDate = q.startDate;
  }
  if (q.endDate) {
    where.push("date(leads.created_at) <= date(@endDate)");
    params.endDate = q.endDate;
  }
  return { where: where.length ? `where ${where.join(" and ")}` : "", params };
}

async function getLead(id, includeDeleted = false) {
  const deleted = includeDeleted ? "" : "and leads.deleted_at is null";
  return await db.get(`${leadSelect} where leads.id = ? ${deleted}`, id);
}

async function listLeads(q, user) {
  const { where, params } = buildLeadQuery(q, user);
  const sort = q.sort === "Recently Updated" ? "leads.updated_at desc" : "leads.created_at desc";
  const limit = Math.min(Number(q.limit || 10), 2000);
  const offset = Math.max(Number(q.offset || 0), 0);
  const rows = await db.all(`${leadSelect} ${where} order by ${sort} limit @limit offset @offset`, { ...params, limit, offset });
  const total = (await db.get(`select count(*) as count from leads left join agencies on agencies.id = leads.agency_id left join ccus on ccus.id = leads.ccu_id ${where}`, params)).count;
  return { rows, total };
}

app.post("/api/auth/login", async (req, res) => {
  const { username, password } = req.body;
  const user = await db.get("select * from users where username = ?", username);
  if (!user || !verifyPassword(password || "", user.hashed_password)) return res.status(401).json({ error: "Invalid credentials" });
  if (!user.is_approved) return res.status(403).json({ error: "Account pending approval" });
  const payload = { sub: user.username, username: user.username, role: user.role, user_id: user.id, employee_id: user.user_id };
  const token = jwt.sign(payload, jwtSecret, { expiresIn: "7d" });
  await logActivity(payload, "USER_LOGIN", "User", user.id, user.username, `User '${user.username}' logged in`, null, null, "auth,login");
  res.json({ token, user: publicUser(user, { profile: true }) });
});

async function getCurrentUser(userId) {
  return cached(cacheKey("user", [userId]), 60_000, () => db.get("select * from users where id = ?", userId));
}

async function lookupPayload() {
  return cached("lookups", 300_000, async () => {
    await ensureLeadSources();
    const [users, approvedUsers, agencies, agencySuboptions, ccus, events, leadSources] = await Promise.all([
      db.all("select id,user_id,username,email,role,is_approved,password_reset_requested,created_at from users order by username", ),
      db.all("select id,user_id,username,email,role from users where is_approved = 1 order by username", ),
      db.all("select * from agencies order by name", ),
      db.all("select * from agency_suboptions order by name", ),
      db.all("select * from ccus order by name", ),
      db.all("select * from events order by event_name", ),
      db.all("select * from lead_sources order by name", )
    ]);
    return { users, approvedUsers, agencies, agencySuboptions, ccus, events, leadSources };
  });
}

async function activityPayload(user, query = {}) {
  const limit = Math.min(Number(query.limit || 100), 500);
  const offset = Math.max(Number(query.offset || 0), 0);
  const where = [];
  const params = { limit, offset };
  if (!isAdminRole(user.role)) {
    where.push("username = @username");
    params.username = user.username;
  } else if (query.username) {
    where.push("username = @username");
    params.username = query.username;
  }
  if (query.actionType) {
    where.push("action_type = @actionType");
    params.actionType = query.actionType;
  }
  if (query.entityType) {
    where.push("entity_type = @entityType");
    params.entityType = query.entityType;
  }
  if (query.startDate) {
    where.push("timestamp >= @startDate");
    params.startDate = query.startDate;
  }
  if (query.endDate) {
    where.push("timestamp <= @endDate");
    params.endDate = `${query.endDate} 23:59:59`;
  }
  if (query.search) {
    where.push("(lower(description) like @search or lower(keywords) like @search or lower(entity_name) like @search)");
    params.search = `%${String(query.search).toLowerCase()}%`;
  }
  const clause = where.length ? `where ${where.join(" and ")}` : "";
  const [totalRow, rows] = await Promise.all([
    db.get(`select count(*) as count from activity_logs ${clause}`, params),
    db.all(`select * from activity_logs ${clause} order by timestamp desc limit @limit offset @offset`, params)
  ]);
  return { rows, total: totalRow?.count || 0 };
}

app.get("/api/auth/me", auth, async (req, res) => {
  const user = await getCurrentUser(req.user.user_id);
  res.json({ user: publicUser(user, { profile: true }) });
});

app.post("/api/auth/logout", auth, async (req, res) => {
  await logActivity(req.user, "USER_LOGOUT", "User", req.user.user_id, req.user.username, `User '${req.user.username}' logged out`, null, null, "auth,logout");
  res.json({ success: true });
});

app.post("/api/auth/signup", async (req, res) => {
  const { user_id, username, email, password } = req.body;
  if (!user_id || !username || !email || !password) return res.status(400).json({ error: "Please fill in all fields" });
  if (String(password).length < 6) return res.status(400).json({ error: "Password must be at least 6 characters" });
  if (!String(email).includes("@")) return res.status(400).json({ error: "Please enter a valid email" });
  if (await db.get("select id from users where user_id=? or username=? or email=?", user_id, username, email)) return res.status(409).json({ error: "User ID, username, or email already exists" });
  await db.run("insert into users (user_id,username,email,hashed_password,role,is_approved,password_reset_requested,created_at) values (?,?,?,?,?,?,?,?)", user_id, username, email, hashPassword(password), "user", 0, 0, now());
  res.status(201).json({ success: true });
});

app.post("/api/auth/forgot", async (req, res) => {
  const { username } = req.body;
  const user = await db.get("select * from users where username=?", username);
  if (!user) return res.status(404).json({ error: "Username not found" });
  await db.run("update users set password_reset_requested=1 where id=?", user.id);
  res.json({ success: true });
});

app.get("/api/lookups", auth, async (req, res) => {
  const payload = await lookupPayload();
  res.json(isSuperAdminRole(req.user.role) ? payload : { ...payload, users: [] });
});

async function notificationRows(user) {
  const notifications = [];
  if (isSuperAdminRole(user.role)) {
    const pendingUsers = await db.all("select id,username,created_at from users where is_approved = 0 order by created_at desc limit 5", );
    pendingUsers.forEach((pendingUser) => notifications.push({
      id: `pending-user-${pendingUser.id}`,
      type: "User approval",
      title: `ID: ${pendingUser.id} | ${pendingUser.username}`,
      message: `${pendingUser.username} is waiting for approval`,
      detail: pendingUser.created_at || "",
      due: pendingUser.created_at || "",
      icon: "user",
      link: "/users",
      done: false
    }));
    const resetUsers = await db.all("select id,username from users where password_reset_requested = 1 order by username limit 5", );
    resetUsers.forEach((resetUser) => notifications.push({
      id: `password-reset-${resetUser.id}`,
      type: "Password reset",
      title: `ID: ${resetUser.id} | ${resetUser.username}`,
      message: `${resetUser.username} requested a password reset`,
      detail: "System Management",
      due: "",
      icon: "user",
      link: "/users",
      done: false
    }));
  }

  const reminderWhere = isAdminRole(user.role)
    ? "deleted_at is null and coalesce(send_reminders,0) = 1"
    : "deleted_at is null and coalesce(send_reminders,0) = 1 and (owner_id = @ownerId or staff_name = @username)";
  const reminders = await db.all(`select id,first_name,last_name,phone,updated_at,referral_sent_date,referral_type,active_client,authorization_received,source,care_status,last_contact_status from leads where ${reminderWhere} order by updated_at desc limit 8`, { ownerId: user.user_id, username: user.username });
  reminders.forEach((lead) => {
    const target = searchTargetForLead(lead);
    const separator = target.targetUrl.includes("?") ? "&" : "?";
    notifications.push({
      id: `lead-reminder-${lead.id}`,
      type: "Lead reminder",
      title: `ID: ${lead.id} | ${`${lead.first_name || ""} ${lead.last_name || ""}`.trim() || "Lead"}`,
      message: reminderNotificationMessage(lead),
      detail: lead.updated_at || lead.referral_sent_date || "",
      due: lead.referral_sent_date || lead.updated_at || "",
      icon: "lead",
      link: `${target.targetUrl}${separator}globalSearch=true`,
      targetPage: target.targetPage,
      done: false
    });
  });

  const recentActivity = await db.all("select id,action_type,entity_type,entity_id,entity_name,description,timestamp,username,old_value,new_value from activity_logs order by timestamp desc limit 5", );
  for (const activity of recentActivity) {
    let link = "/activity";
    let targetPage = "Activity Logs";
    let title = activity.entity_id && activity.entity_name
      ? `ID: ${activity.entity_id} | ${activity.entity_name}`
      : activity.entity_name || "Recent activity";
    if (activity.entity_type === "Lead" && activity.entity_id) {
      const lead = await db.get("select id,first_name,last_name,active_client,authorization_received,source,care_status from leads where id=?", activity.entity_id);
      if (lead) {
        const target = searchTargetForLead(lead);
        const separator = target.targetUrl.includes("?") ? "&" : "?";
        link = `${target.targetUrl}${separator}globalSearch=true`;
        targetPage = target.targetPage;
        title = `ID: ${lead.id} | ${`${lead.first_name || ""} ${lead.last_name || ""}`.trim() || activity.entity_name || "Lead"}`;
        activity.lead_active_client = lead.active_client;
      }
    }
    notifications.push({
      id: `activity-${activity.id}`,
      type: "Activity",
      title,
      message: activityNotificationMessage(activity),
      detail: activity.timestamp || "",
      due: activity.timestamp || "",
      icon: "activity",
      link,
      targetPage,
      done: true
    });
  }

  return notifications.slice(0, 12);
}

app.get("/api/notifications", auth, async (req, res) => {
  res.json(await notificationsPayload(req.user));
});

async function notificationsPayload(user) {
  const [all, readRows] = await Promise.all([
    cached(cacheKey("notifications-base", [user.role, user.user_id, user.username]), 30_000, () => notificationRows(user)),
    db.all("select notification_id from notification_reads where user_id=?", user.user_id)
  ]);
  const readIds = new Set(readRows.map((row) => row.notification_id));
  const notifications = all
    .filter((item) => !readIds.has(item.id))
    .map((item) => ({ ...item, read: false }));
  return { count: notifications.length, notifications, total: notifications.length };
}

app.get("/api/bootstrap", auth, async (req, res) => {
  const [user, lookups, notifications, activity] = await Promise.all([
    getCurrentUser(req.user.user_id),
    lookupPayload(),
    notificationsPayload(req.user),
    activityPayload(req.user, { limit: 4, offset: 0 })
  ]);
  res.json({ user: publicUser(user, { profile: true }), lookups, notifications, activity });
});

app.post("/api/notifications/read-all", auth, async (req, res) => {
  const rows = await notificationRows(req.user);
  for (const item of rows) {
    await db.run("insert or replace into notification_reads (user_id,notification_id,read_at) values (?,?,?)", req.user.user_id, item.id, now());
  }
  res.json({ success: true, count: 0, notifications: [] });
});

app.post("/api/notifications/read", auth, async (req, res) => {
  if (!req.body.id) return res.status(400).json({ error: "Missing notification id" });
  await db.run("insert or replace into notification_reads (user_id,notification_id,read_at) values (?,?,?)", req.user.user_id, req.body.id, now());
  res.json({ success: true });
});

app.get("/api/leads", auth, async (req, res) => res.json(await listLeads(req.query, req.user)));
app.get("/api/leads/:id", auth, async (req, res) => {
  const lead = await getLead(req.params.id, true);
  if (!lead) return res.status(404).json({ error: "Lead not found" });
  const comments = await db.all("select * from lead_comments where lead_id = ? order by created_at desc", req.params.id);
  const attachments = await db.all("select * from attachments where lead_id = ? order by uploaded_at desc", req.params.id);
  res.json({ lead, comments, attachments });
});

function requireExternalLeadApiKey(req, res) {
  if (!externalLeadApiKey) {
    res.status(503).json({ error: "External lead form is not configured" });
    return false;
  }
  if (req.headers["x-api-key"] !== externalLeadApiKey) {
    res.status(401).json({ error: "Invalid API key" });
    return false;
  }
  return true;
}

app.get("/api/external-lead/staff", async (req, res) => {
  if (!requireExternalLeadApiKey(req, res)) return;
  const staff = await db.all("select user_id,username from users where is_approved = 1 and user_id is not null order by username");
  res.json({ staff });
});

app.post("/api/external-lead", async (req, res) => {
  if (!requireExternalLeadApiKey(req, res)) return;

  const body = req.body || {};
  const required = ["staff_name", "user_id", "first_name", "last_name", "gender", "medicaid", "source", "phone"];
  const missing = required.filter((field) => !String(body[field] || "").trim());
  if (missing.length) return res.status(400).json({ error: `Missing required fields: ${missing.join(", ")}` });

  const user = await db.get("select id,user_id,username from users where user_id = ?", String(body.user_id).trim());
  if (!user) return res.status(400).json({ error: `Staff ID '${body.user_id}' was not found` });
  if (user.username !== String(body.staff_name).trim()) {
    return res.status(400).json({ error: "Staff name does not match Staff ID" });
  }

  const fullAddress = [body.address_line1, body.address_line2].map((value) => String(value || "").trim()).filter(Boolean).join(", ");
  const isTransfer = body.source === "Transfer";
  const data = {
    created_at: now(),
    updated_at: now(),
    created_by: user.username,
    updated_by: user.username,
    owner_id: user.id,
    staff_name: user.username,
    first_name: String(body.first_name).trim(),
    last_name: String(body.last_name).trim(),
    source: String(body.source).trim(),
    active_client: bool(isTransfer),
    authorization_received: bool(isTransfer),
    care_status: isTransfer ? "Transfer Received" : null,
    soc_date: body.soc_date || null,
    phone: String(body.phone).trim(),
    street: fullAddress || null,
    address: fullAddress || null,
    city: body.city || null,
    state: body.state || null,
    zip_code: body.zip || null,
    dob: body.birthdate || null,
    age: body.age || null,
    medicaid_status: body.medicaid,
    medicaid_no: body.medicaid_number || null,
    gender: String(body.gender).trim(),
    comments: body.info || null,
    email: body.email || null,
    custom_user_id: user.user_id,
    last_contact_status: "Initial Call",
    priority: "Not Called",
    send_reminders: 1
  };

  const duplicate = await findDuplicateLead(data);
  if (duplicate) return res.status(409).json({ error: "Duplicate lead detected", duplicate });

  const fields = Object.keys(data);
  const result = await db.run(`insert into leads (${fields.join(",")}) values (${fields.map((field) => `@${field}`).join(",")})`, data);
  const lead = await getLead(result.lastInsertRowid, true);
  await logActivity(user, "CREATE_LEAD", "Lead", lead.id, `${lead.first_name} ${lead.last_name}`, `Created lead '${lead.first_name} ${lead.last_name}' from external form`, null, lead, "lead,create,external-form");
  res.status(201).json({ success: true, lead_id: lead.id, lead });
});

app.get("/api/search/suggestions", auth, async (req, res) => {
  const query = String(req.query.q || "").trim().toLowerCase();
  const { rows } = await listLeads({ search: query, includeDeleted: false, active: "All", limit: 50 }, req.user);
  rows.sort((left, right) => searchSuggestionRelevance(left, query) - searchSuggestionRelevance(right, query) || String(right.created_at || "").localeCompare(String(left.created_at || "")));
  res.json({ clients: rows.slice(0, 10).map((l) => {
    const target = searchTargetForLead(l);
    const separator = target.targetUrl.includes("?") ? "&" : "?";
    return { id: l.id, name: `${l.first_name} ${l.last_name}`, phone: l.phone, ...target, targetUrl: `${target.targetUrl}${separator}globalSearch=true` };
  }) });
});

app.post("/api/leads", auth, async (req, res) => {
  const body = req.body;
  const duplicate = await findDuplicateLead(body);
  if (duplicate) {
    const kind = duplicateKind(duplicate);
    const payloadKey = duplicate.deleted_at ? "deletedDuplicate" : "duplicate";
    return res.status(409).json({ error: `Duplicate ${kind.charAt(0).toUpperCase()}${kind.slice(1)} Detected`, [payloadKey]: duplicate, duplicateKind: kind });
  }
  const fields = ["created_at","updated_at","created_by","updated_by","owner_id","staff_name","first_name","last_name","source","event_name","word_of_mouth_type","other_source_type","active_client","referral_type","agency_id","agency_suboption_id","ccu_id","authorization_received","care_status","priority","tag_color","soc_date","phone","street","city","zip_code","dob","age","gender","medicaid_no","e_contact_name","e_contact_relation","e_contact_phone","last_contact_status","comments","ssn","email","custom_user_id","state","send_reminders","caregiver_type","referral_sent_date"];
  const data = { ...body, created_at: now(), updated_at: now(), created_by: req.user.username, updated_by: req.user.username, priority: body.priority || "Not Called", tag_color: body.tag_color || null, active_client: bool(body.active_client), authorization_received: bool(body.authorization_received), send_reminders: 1, referral_sent_date: body.active_client ? (body.referral_sent_date || now().slice(0, 10)) : null };
  const sql = `insert into leads (${fields.join(",")}) values (${fields.map((f) => `@${f}`).join(",")})`;
  const result = await db.run(sql, data);
  const lead = await getLead(result.lastInsertRowid, true);
  await logActivity(req.user, "CREATE_LEAD", "Lead", lead.id, `${lead.first_name} ${lead.last_name}`, `Created lead '${lead.first_name} ${lead.last_name}'`, null, lead, "lead,create");
  res.status(201).json({ lead });
});

app.patch("/api/leads/:id", auth, async (req, res) => {
  const oldLead = await getLead(req.params.id, true);
  if (!oldLead) return res.status(404).json({ error: "Lead not found" });
  const allowed = Object.keys(req.body).filter((k) => leadWriteFields.has(k));
  if (!allowed.length) return res.json({ lead: oldLead });
  const data = Object.fromEntries(allowed.map((key) => [key, req.body[key]]));
  data.id = req.params.id;
  data.updated_at = now();
  data.updated_by = req.user.username;
  const sets = [...allowed, "updated_at", "updated_by"].map((k) => `${k} = @${k}`).join(",");
  await db.run(`update leads set ${sets} where id = @id`, data);
  const lead = await getLead(req.params.id, true);
  const actionType = req.body.care_status === "Care Start"
    ? "CARE_START_MARKED"
    : Number(req.body.authorization_received) === 1
      ? "AUTHORIZATION_MARKED"
      : Number(req.body.active_client) === 1 && Number(req.body.authorization_received) === 0
        ? "REFERRAL_MARKED"
        : "UPDATE_LEAD";
  const changedFields = changedNotificationFields(oldLead, lead);
  const description = changedFields.length === 1
    ? `${changedFields[0].label} changed from "${changedFields[0].before}" to "${changedFields[0].after}" for '${lead.first_name} ${lead.last_name}'`
    : changedFields.length > 1
      ? `Updated ${changedFields.length} fields for '${lead.first_name} ${lead.last_name}': ${changedFields.slice(0, 3).map((field) => field.label).join(", ")}${changedFields.length > 3 ? ", ..." : ""}`
      : actionType === "CARE_START_MARKED"
        ? `Marked Care Start for '${lead.first_name} ${lead.last_name}'`
        : actionType === "AUTHORIZATION_MARKED"
          ? `Marked authorization for '${lead.first_name} ${lead.last_name}'`
          : actionType === "REFERRAL_MARKED"
            ? `Marked referral for '${lead.first_name} ${lead.last_name}'`
            : `Updated lead '${lead.first_name} ${lead.last_name}'`;
  await logActivity(req.user, actionType, "Lead", lead.id, `${lead.first_name} ${lead.last_name}`, description, oldLead, lead, "lead,update");
  res.json({ lead });
});

app.post("/api/leads/:id/soft-delete", auth, async (req, res) => {
  const lead = await getLead(req.params.id, true);
  await db.run("update leads set deleted_at=@deleted_at, deleted_by=@deleted_by, updated_at=@updated_at, updated_by=@updated_by where id=@id", { id: req.params.id, deleted_at: now(), deleted_by: req.user.username, updated_at: now(), updated_by: req.user.username });
  await logActivity(req.user, "DELETE_LEAD", "Lead", Number(req.params.id), lead ? `${lead.first_name} ${lead.last_name}` : "", "Soft deleted lead", lead, null, "lead,delete");
  res.json({ success: true });
});

app.post("/api/leads/:id/restore", auth, async (req, res) => {
  await db.run("update leads set deleted_at=null, deleted_by=null, updated_at=@updated_at, updated_by=@updated_by where id=@id", { id: req.params.id, updated_at: now(), updated_by: req.user.username });
  const lead = await getLead(req.params.id, true);
  await logActivity(req.user, "RESTORE_LEAD", "Lead", lead.id, `${lead.first_name} ${lead.last_name}`, "Restored lead", null, lead, "lead,restore");
  res.json({ lead });
});

app.delete("/api/leads/:id", auth, admin, async (req, res) => {
  await db.run("delete from leads where id = ?", req.params.id);
  await logActivity(req.user, "PERMANENT_DELETE", "Lead", Number(req.params.id), "", "Permanently deleted lead", null, null, "lead,delete");
  res.json({ success: true });
});

app.post("/api/leads/:id/comment", auth, async (req, res) => {
  const lead = await db.get("select id,first_name,last_name from leads where id=?", req.params.id);
  const result = await db.run("insert into lead_comments (lead_id,username,content,created_at) values (?,?,?,?)", req.params.id, req.user.username, req.body.content, now());
  await logActivity(req.user, "ADD_COMMENT", "Lead", Number(req.params.id), lead ? `${lead.first_name || ""} ${lead.last_name || ""}`.trim() : "", "Added comment", null, { content: req.body.content }, "lead,comment");
  res.status(201).json({ comment: await db.get("select * from lead_comments where id=?", result.lastInsertRowid) });
});

app.post("/api/leads/:id/attachment", auth, upload.single("file"), async (req, res) => {
  const safeName = `${req.params.id}_${req.file.originalname}`;
  const finalPath = path.join(uploadsDir, safeName);
  fs.renameSync(req.file.path, finalPath);
  const result = await db.run("insert into attachments (lead_id,filename,file_path,file_size,uploaded_by,uploaded_at) values (?,?,?,?,?,?)", req.params.id, req.file.originalname, finalPath, req.file.size, req.user.username, now());
  const attachment = await db.get("select * from attachments where id=?", result.lastInsertRowid);
  await logActivity(req.user, "UPLOAD_ATTACHMENT", "Lead", Number(req.params.id), req.file.originalname, `Uploaded attachment '${req.file.originalname}'`, null, attachment, "lead,attachment,upload");
  res.status(201).json({ attachment });
});

app.get("/api/attachments/:id/preview", auth, async (req, res) => {
  const att = await db.get("select * from attachments where id=?", req.params.id);
  const filePath = resolveAttachmentPath(att);
  if (!filePath) return res.status(404).json({ error: "File not found" });
  res.type(att.filename);
  res.setHeader("Content-Disposition", `inline; filename="${encodeURIComponent(att.filename)}"`);
  res.sendFile(filePath);
});

app.get("/api/attachments/:id/download", auth, async (req, res) => {
  const att = await db.get("select * from attachments where id=?", req.params.id);
  const filePath = resolveAttachmentPath(att);
  if (!filePath) return res.status(404).json({ error: "File not found" });
  res.download(filePath, att.filename);
});

app.delete("/api/attachments/:id", auth, admin, async (req, res) => {
  const att = await db.get("select * from attachments where id=?", req.params.id);
  const filePath = resolveAttachmentPath(att);
  if (filePath) fs.unlinkSync(filePath);
  await db.run("delete from attachments where id=?", req.params.id);
  await logActivity(req.user, "DELETE_ATTACHMENT", "Lead", att?.lead_id || null, att?.filename || "", `Deleted attachment '${att?.filename || req.params.id}'`, att, null, "lead,attachment,delete");
  res.json({ success: true });
});

app.get("/api/activity", auth, async (req, res) => {
  res.json(await activityPayload(req.user, req.query));
});

app.get("/api/leads/:id/history", auth, async (req, res) => {
  res.json({ rows: await db.all("select * from activity_logs where entity_type='Lead' and entity_id=? order by timestamp desc limit 20", req.params.id) });
});

async function dashboardPayload(user, query = {}) {
  const includeUsers = query.includeUsers === "true" || query.includeUsers === true;
  const isCumulative = isAdminRole(user.role) || query.mode === "cumulative";
  const cacheScope = isCumulative ? "all" : `user-${user.user_id}-${user.username}`;
  return cached(cacheKey("dashboard", [cacheScope, includeUsers ? "users" : "base"]), includeUsers ? 60_000 : 120_000, async () => {
  const leadRows = await db.all(`${leadSelect} where leads.deleted_at is null`, );
  const visible = isCumulative ? leadRows : leadRows.filter((l) => l.staff_name === user.username || l.owner_id === user.user_id);
  const hydrate = (row) => ({
    ...row,
    full_name: `${row.first_name || ""} ${row.last_name || ""}`.trim(),
    month: String(row.created_at || "").slice(0, 7) || "N/A",
    ccu_name: row.ccu_name || "N/A",
    agency_name: row.agency_name || "N/A",
    auth_label: row.authorization_received ? "Authorized" : "Pending",
    referral_label: row.active_client ? "Referrals" : "Pending"
  });
  const rows = visible.map(hydrate);
  const group = (key, sourceRows = rows) => Object.values(sourceRows.reduce((acc, row) => {
    const name = row[key] || "N/A";
    acc[name] = acc[name] || { name, count: 0, rowIds: [] };
    acc[name].count += 1;
    acc[name].rowIds.push(row.id);
    return acc;
  }, {})).sort((a, b) => b.count - a.count || String(a.name).localeCompare(String(b.name)));
  const only = (predicate) => rows.filter(predicate);
  const referrals = only((l) => Number(l.active_client) === 1);
  const pendingLeads = only((l) => Number(l.active_client) !== 1);
  const careStart = referrals.filter((l) => l.care_status === "Care Start");
  const notStart = referrals.filter((l) => l.care_status === "Not Start");
  const pendingCare = referrals.filter((l) => !["Care Start", "Not Start"].includes(l.care_status));
  const [totalUsersRow, approvedUsers] = await Promise.all([
    db.get("select count(*) as count from users", ),
    includeUsers ? db.all("select id,user_id,username,email,role from users where is_approved = 1 order by username", ) : Promise.resolve([])
  ]);
  const userDashboards = includeUsers ? approvedUsers.map((u) => {
    const userRows = rows.filter((l) => l.staff_name === u.username || l.owner_id === u.id);
    return {
      user: u,
      stats: { total_leads: userRows.length, referrals: userRows.filter((l) => Number(l.active_client) === 1).length },
      source: group("source", userRows),
      status: group("last_contact_status", userRows),
      rowIds: userRows.map((row) => row.id)
    };
  }) : [];
  return {
    stats: {
      total_leads: rows.length,
      total_users: totalUsersRow?.count || 0,
      active_clients: referrals.length
    },
    charts: {
      staff: group("staff_name"),
      source: group("source"),
      status: group("last_contact_status"),
      month: group("month"),
      event: group("event_name", rows.filter((l) => l.source === "Event")),
      wordOfMouth: group("word_of_mouth_type", rows.filter((l) => l.source === "Word of Mouth")),
      priority: group("priority"),
      auth: group("auth_label"),
      ccuSent: group("ccu_name", referrals),
      ccuConfirmed: group("ccu_name", referrals.filter((l) => l.care_status === "Care Start" || Number(l.authorization_received) === 1)),
      referralConfirmation: [
        { name: "Referrals", count: referrals.length, rowIds: referrals.map((row) => row.id) },
        { name: "Pending", count: pendingLeads.length, rowIds: pendingLeads.map((row) => row.id) }
      ],
      leadConversion: [
        { name: "Care Start", count: careStart.length, rowIds: careStart.map((row) => row.id) },
        { name: "Not Start", count: notStart.length, rowIds: notStart.map((row) => row.id) },
        { name: "Pending", count: pendingCare.length, rowIds: pendingCare.map((row) => row.id) }
      ]
    },
    rates: {
      confirmation: rows.length ? (referrals.length / rows.length) * 100 : 0,
      conversion: referrals.length ? (careStart.length / referrals.length) * 100 : 0
    },
    rows,
    userDashboards
  };
  });
}

app.get("/api/dashboard", auth, async (req, res) => {
  res.json(await dashboardPayload(req.user, req.query));
});

app.get("/api/reports/export", auth, async (req, res) => {
  const { rows } = await listLeads({ ...req.query, limit: 2000 }, req.user);
  if (req.query.format === "word") {
    const tableColumns = [
      { header: "ID", key: "id", width: 900 },
      { header: "Name", key: "name", width: 2800 },
      { header: "Staff", key: "staff_name", width: 2200 },
      { header: "Source", key: "source", width: 2400 },
      { header: "Status", key: "last_contact_status", width: 2500 },
      { header: "Phone", key: "phone", width: 1900 }
    ];
    const wordRows = rows.map((lead) => ({
      id: lead.id,
      name: `${lead.first_name || ""} ${lead.last_name || ""}`.trim(),
      staff_name: lead.staff_name,
      source: lead.source,
      last_contact_status: lead.last_contact_status,
      phone: lead.phone
    }));
    const headerRow = new TableRow({
      children: tableColumns.map((column) => new TableCell({
        width: { size: column.width, type: WidthType.DXA },
        children: [new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: column.header, bold: true, size: 22 })]
        })]
      }))
    });
    const dataRows = wordRows.map((row) => new TableRow({
      children: tableColumns.map((column) => new TableCell({
        width: { size: column.width, type: WidthType.DXA },
        children: [new Paragraph({
          children: [new TextRun({ text: String(row[column.key] || "N/A"), size: 20 })]
        })]
      }))
    }));
    const doc = new Document({
      sections: [{
        properties: {
          page: {
            margin: { top: 720, right: 720, bottom: 720, left: 720 },
            size: { orientation: PageOrientation.LANDSCAPE }
          }
        },
        children: [
          new Paragraph({
            spacing: { after: 180 },
            children: [new TextRun({ text: "Lead Manager Report", bold: true, size: 34 })]
          }),
          new Paragraph({
            spacing: { after: 240 },
            children: [new TextRun({
              text: `Generated ${new Date().toLocaleString()} | Total records: ${wordRows.length}`,
              size: 20
            })]
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            layout: TableLayoutType.FIXED,
            rows: [headerRow, ...dataRows]
          })
        ]
      }]
    });
    const buffer = await Packer.toBuffer(doc);
    res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
    res.setHeader("Content-Disposition", `attachment; filename=lead_report_${Date.now()}.docx`);
    return res.send(buffer);
  }
  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet("Leads");
  sheet.columns = ["ID", "First Name", "Last Name", "Staff", "Source", "Status", "Call Status", "Phone", "Email", "CCU", "Payor", "Created", "Updated"].map((h) => ({ header: h, key: h, width: 20 }));
  rows.forEach((l) => sheet.addRow({ "ID": l.id, "First Name": l.first_name, "Last Name": l.last_name, "Staff": l.staff_name, "Source": l.source, "Status": l.last_contact_status, "Call Status": l.priority, "Phone": l.phone, "Email": l.email, "CCU": l.ccu_name, "Payor": l.agency_name, "Created": l.created_at, "Updated": l.updated_at }));
  const buffer = await workbook.xlsx.writeBuffer();
  res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
  res.setHeader("Content-Disposition", `attachment; filename=leads_export_${Date.now()}.xlsx`);
  res.send(buffer);
});

app.post("/api/reports/word", auth, async (req, res) => {
  const title = String(req.body?.title || "Lead Manager Report");
  const rows = Array.isArray(req.body?.rows) ? req.body.rows : [];
  const columns = Object.keys(rows[0] || { Empty: "" });
  const width = Math.floor(14000 / Math.max(columns.length, 1));
  const headerRow = new TableRow({
    children: columns.map((column) => new TableCell({
      width: { size: width, type: WidthType.DXA },
      children: [new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [new TextRun({ text: column, bold: true, size: 22 })]
      })]
    }))
  });
  const dataRows = rows.map((row) => new TableRow({
    children: columns.map((column) => new TableCell({
      width: { size: width, type: WidthType.DXA },
      children: [new Paragraph({
        children: [new TextRun({ text: String(row[column] ?? "N/A"), size: 20 })]
      })]
    }))
  }));
  const doc = new Document({
    sections: [{
      properties: {
        page: {
          margin: { top: 720, right: 720, bottom: 720, left: 720 },
          size: { orientation: PageOrientation.LANDSCAPE }
        }
      },
      children: [
        new Paragraph({
          spacing: { after: 180 },
          children: [new TextRun({ text: title, bold: true, size: 34 })]
        }),
        new Paragraph({
          spacing: { after: 240 },
          children: [new TextRun({
            text: `Generated ${new Date().toLocaleString()} | Total records: ${rows.length}`,
            size: 20
          })]
        }),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          layout: TableLayoutType.FIXED,
          rows: [headerRow, ...dataRows]
        })
      ]
    }]
  });
  const buffer = await Packer.toBuffer(doc);
  res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
  res.setHeader("Content-Disposition", `attachment; filename=${title.toLowerCase().replace(/[^a-z0-9]+/gi, "_")}.docx`);
  res.send(buffer);
});

app.patch("/api/users/:id", auth, async (req, res, next) => {
  if (req.params.id === "me") return next();
  if (!isSuperAdminRole(req.user.role)) return res.status(403).json({ error: "Super admin only" });
  const oldUser = await db.get("select * from users where id=?", req.params.id);
  if (!oldUser) return res.status(404).json({ error: "User not found" });
  const allowed = ["username", "role", "is_approved", "password_reset_requested", "email", "user_id", "profile_pic"];
  const keys = Object.keys(req.body).filter((k) => allowed.includes(k));
  if (!keys.length) return res.json({ success: true });
  if (Object.prototype.hasOwnProperty.call(req.body, "role") && !["user", "admin", "super_admin"].includes(req.body.role)) {
    return res.status(400).json({ error: "Invalid role" });
  }
  if (oldUser.role === "super_admin" && req.body.role && req.body.role !== "super_admin") {
    const superCount = await db.get("select count(*) as count from users where role='super_admin'");
    if (Number(superCount?.count || 0) <= 1) return res.status(400).json({ error: "At least one super admin is required" });
  }
  await db.run(`update users set ${keys.map((k) => `${k}=@${k}`).join(",")} where id=@id`, { ...req.body, id: req.params.id });
  const updatedUser = await db.get("select * from users where id=?", req.params.id);
  await logActivity(req.user, req.body.is_approved === 1 && oldUser?.is_approved !== 1 ? "USER_APPROVED" : "UPDATE_USER", "User", Number(req.params.id), updatedUser?.username || "", `Updated user '${updatedUser?.username || req.params.id}'`, publicUser(oldUser), publicUser(updatedUser), "user,update");
  res.json({ user: publicUser(updatedUser, { profile: true }) });
});

app.patch("/api/users/me", auth, async (req, res) => {
  const allowed = ["username", "email", "user_id", "profile_pic"];
  const keys = Object.keys(req.body).filter((k) => allowed.includes(k));
  if (!keys.length) return res.json({ user: publicUser(await db.get("select * from users where id=?", req.user.user_id), { profile: true }) });
  const oldUser = await db.get("select * from users where id=?", req.user.user_id);
  await db.run(`update users set ${keys.map((k) => `${k}=@${k}`).join(",")} where id=@id`, { ...req.body, id: req.user.user_id });
  const user = await db.get("select * from users where id=?", req.user.user_id);
  await logActivity(req.user, "UPDATE_PROFILE", "User", req.user.user_id, user?.username || req.user.username, `Updated profile for '${user?.username || req.user.username}'`, publicUser(oldUser), publicUser(user), "user,profile,update");
  res.json({ user: publicUser(user, { profile: true }) });
});

app.post("/api/users/me/password", auth, async (req, res) => {
  const { currentPassword, newPassword } = req.body;
  const user = await db.get("select * from users where id=?", req.user.user_id);
  if (!user || !verifyPassword(currentPassword || "", user.hashed_password)) return res.status(400).json({ error: "Current password is incorrect" });
  if (!newPassword || String(newPassword).length < 6) return res.status(400).json({ error: "Password must be at least 6 characters" });
  await db.run("update users set hashed_password=?, password_reset_requested=0 where id=?", hashPassword(newPassword), req.user.user_id);
  await logActivity(req.user, "PASSWORD_CHANGED", "User", req.user.user_id, user.username, `Password changed for '${user.username}'`, null, null, "user,password");
  res.json({ success: true });
});

app.post("/api/users/me/request-reset", auth, async (req, res) => {
  await db.run("update users set password_reset_requested=1 where id=?", req.user.user_id);
  await logActivity(req.user, "PASSWORD_RESET_REQUESTED", "User", req.user.user_id, req.user.username, `Password reset requested by '${req.user.username}'`, null, null, "user,password,reset");
  res.json({ success: true });
});

app.post("/api/users", auth, superAdmin, async (req, res) => {
  const { user_id, username, email, password, role } = req.body;
  if (!user_id || !username || !email || !password) return res.status(400).json({ error: "Please fill in all required fields" });
  const nextRole = role || "user";
  if (!["user", "admin", "super_admin"].includes(nextRole)) return res.status(400).json({ error: "Invalid role" });
  if (await db.get("select id from users where user_id=? or username=? or email=?", user_id, username, email)) return res.status(409).json({ error: "User ID, username, or email already exists" });
  const result = await db.run("insert into users (user_id,username,email,hashed_password,role,is_approved,password_reset_requested,created_at) values (?,?,?,?,?,?,?,?)", user_id, username, email, hashPassword(password), nextRole, 1, 0, now());
  const createdUser = await db.get("select * from users where id=?", result.lastInsertRowid);
  await logActivity(req.user, "CREATE_USER", "User", createdUser.id, createdUser.username, `Created user '${createdUser.username}'`, null, publicUser(createdUser), "user,create");
  res.status(201).json({ user: publicUser(createdUser) });
});

app.post("/api/users/:id/reset-password", auth, superAdmin, async (req, res) => {
  if (!req.body.password || String(req.body.password).length < 6) return res.status(400).json({ error: "Password must be at least 6 characters" });
  const targetUser = await db.get("select * from users where id=?", req.params.id);
  await db.run("update users set hashed_password=?, password_reset_requested=0 where id=?", hashPassword(req.body.password), req.params.id);
  await logActivity(req.user, "PASSWORD_RESET", "User", Number(req.params.id), targetUser?.username || "", `Reset password for '${targetUser?.username || req.params.id}'`, null, null, "user,password,reset");
  res.json({ success: true });
});

app.delete("/api/users/:id", auth, superAdmin, async (req, res) => {
  const deletedUser = await db.get("select * from users where id=?", req.params.id);
  if (!deletedUser) return res.status(404).json({ error: "User not found" });
  if (Number(req.params.id) === Number(req.user.user_id)) return res.status(400).json({ error: "You cannot delete your own account" });
  if (deletedUser.role === "super_admin") {
    const superCount = await db.get("select count(*) as count from users where role='super_admin'");
    if (Number(superCount?.count || 0) <= 1) return res.status(400).json({ error: "At least one super admin is required" });
  }
  await db.run("delete from users where id=?", req.params.id);
  await logActivity(req.user, "DELETE_USER", "User", Number(req.params.id), deletedUser?.username || "", `Deleted user '${deletedUser?.username || req.params.id}'`, publicUser(deletedUser), null, "user,delete");
  res.json({ success: true });
});

app.post("/api/admin/:type", auth, admin, async (req, res) => {
  const table = { event: "events", agency: "agencies", ccu: "ccus", source: "lead_sources" }[req.params.type];
  if (!table) return res.status(400).json({ error: "Bad type" });
  const name = String(req.body.name || "").trim();
  if (!name) return res.status(400).json({ error: "Name is required" });
  const duplicate = table === "events"
    ? await db.get("select id from events where lower(event_name)=lower(?)", name)
    : await db.get(`select id from ${table} where lower(name)=lower(?)`, name);
  if (duplicate) {
    const label = req.params.type === "agency" ? "Payor" : req.params.type === "ccu" ? "CCU" : req.params.type === "source" ? "Source" : "Event";
    return res.status(409).json({ error: `${label} already exists` });
  }
  req.body.name = name;
  if (table === "events") await db.run("insert into events (event_name,created_at,created_by) values (?,?,?)", req.body.name, now(), req.user.username);
  if (table === "agencies") await db.run("insert into agencies (name,address,phone,fax,email,created_at,created_by) values (@name,@address,@phone,@fax,@email,@created_at,@created_by)", { ...req.body, created_at: now(), created_by: req.user.username });
  if (table === "ccus") await db.run("insert into ccus (name,street,city,state,zip_code,phone,fax,email,care_coordinator_name,created_at,created_by) values (@name,@street,@city,@state,@zip_code,@phone,@fax,@email,@care_coordinator_name,@created_at,@created_by)", { ...req.body, created_at: now(), created_by: req.user.username });
  if (table === "lead_sources") await db.run("insert into lead_sources (name,created_at,created_by) values (?,?,?)", req.body.name, now(), req.user.username);
  await logActivity(req.user, `CREATE_${req.params.type.toUpperCase()}`, req.params.type === "agency" ? "Payor" : req.params.type === "source" ? "Source" : req.params.type.toUpperCase(), null, req.body.name || "", `Created ${req.params.type} '${req.body.name || ""}'`, null, req.body, `${req.params.type},create`);
  res.status(201).json({ success: true });
});

app.post("/api/ccus", auth, async (req, res) => {
  if (!req.body.name) return res.status(400).json({ error: "CCU name is required" });
  if (await db.get("select id from ccus where lower(name)=lower(?)", req.body.name)) return res.status(409).json({ error: "CCU already exists" });
  await db.run("insert into ccus (name,street,city,state,zip_code,phone,fax,email,care_coordinator_name,created_at,created_by) values (@name,@street,@city,@state,@zip_code,@phone,@fax,@email,@care_coordinator_name,@created_at,@created_by)", {
    ...req.body,
    created_at: now(),
    created_by: req.user.username
  });
  await logActivity(req.user, "CREATE_CCU", "CCU", null, req.body.name, `Created CCU '${req.body.name}'`, null, req.body, "ccu,create");
  res.status(201).json({ success: true });
});

app.patch("/api/agencies/:id", auth, async (req, res) => {
  const allowed = ["name", "address", "phone", "fax", "email"];
  const keys = Object.keys(req.body).filter((key) => allowed.includes(key));
  if (!keys.length) return res.json({ success: true });
  const oldAgency = await db.get("select * from agencies where id=?", req.params.id);
  await db.run(`update agencies set ${keys.map((key) => `${key}=@${key}`).join(",")} where id=@id`, { ...req.body, id: req.params.id });
  const agency = await db.get("select * from agencies where id=?", req.params.id);
  await logActivity(req.user, "UPDATE_PAYOR", "Payor", Number(req.params.id), agency?.name || "", `Updated payor '${agency?.name || req.params.id}'`, oldAgency, agency, "payor,update");
  res.json({ success: true });
});

app.patch("/api/ccus/:id", auth, async (req, res) => {
  const allowed = ["name", "street", "city", "state", "zip_code", "phone", "fax", "email", "care_coordinator_name"];
  const keys = Object.keys(req.body).filter((key) => allowed.includes(key));
  if (!keys.length) return res.json({ success: true });
  const oldCcu = await db.get("select * from ccus where id=?", req.params.id);
  await db.run(`update ccus set ${keys.map((key) => `${key}=@${key}`).join(",")} where id=@id`, { ...req.body, id: req.params.id });
  const ccu = await db.get("select * from ccus where id=?", req.params.id);
  await logActivity(req.user, "UPDATE_CCU", "CCU", Number(req.params.id), ccu?.name || "", `Updated CCU '${ccu?.name || req.params.id}'`, oldCcu, ccu, "ccu,update");
  res.json({ success: true });
});

app.patch("/api/admin/event/:id", auth, admin, async (req, res) => {
  const eventName = String(req.body.name || req.body.event_name || "").trim();
  if (!eventName) return res.status(400).json({ error: "Event name is required" });
  const duplicate = await db.get("select id from events where lower(event_name)=lower(?) and id != ?", eventName, req.params.id);
  if (duplicate) return res.status(409).json({ error: "Event already exists" });
  const oldEvent = await db.get("select * from events where id=?", req.params.id);
  await db.run("update events set event_name=? where id=?", eventName, req.params.id);
  const event = await db.get("select * from events where id=?", req.params.id);
  await logActivity(req.user, "UPDATE_EVENT", "EVENT", Number(req.params.id), event?.event_name || "", `Updated event '${event?.event_name || req.params.id}'`, oldEvent, event, "event,update");
  res.json({ success: true });
});

app.patch("/api/admin/source/:id", auth, admin, async (req, res) => {
  const sourceName = String(req.body.name || "").trim();
  if (!sourceName) return res.status(400).json({ error: "Source name is required" });
  const duplicate = await db.get("select id from lead_sources where lower(name)=lower(?) and id != ?", sourceName, req.params.id);
  if (duplicate) return res.status(409).json({ error: "Source already exists" });
  const oldSource = await db.get("select * from lead_sources where id=?", req.params.id);
  await db.run("update lead_sources set name=?,updated_at=?,updated_by=? where id=?", sourceName, now(), req.user.username, req.params.id);
  const source = await db.get("select * from lead_sources where id=?", req.params.id);
  await logActivity(req.user, "UPDATE_SOURCE", "Source", Number(req.params.id), source?.name || "", `Updated source '${source?.name || req.params.id}'`, oldSource, source, "source,update");
  res.json({ success: true });
});

app.delete("/api/admin/:type/:id", auth, admin, async (req, res) => {
  const table = { event: "events", agency: "agencies", ccu: "ccus", source: "lead_sources" }[req.params.type];
  if (!table) return res.status(400).json({ error: "Bad type" });
  const nameColumn = table === "events" ? "event_name" : "name";
  const oldItem = await db.get(`select * from ${table} where id=?`, req.params.id);
  await db.run(`delete from ${table} where id=?`, req.params.id);
  await logActivity(req.user, `DELETE_${req.params.type.toUpperCase()}`, req.params.type === "agency" ? "Payor" : req.params.type === "source" ? "Source" : req.params.type.toUpperCase(), Number(req.params.id), oldItem?.[nameColumn] || "", `Deleted ${req.params.type} '${oldItem?.[nameColumn] || req.params.id}'`, oldItem, null, `${req.params.type},delete`);
  res.json({ success: true });
});

function spaHtml() {
  const indexPath = path.join(distDir, "index.html");
  let html = fs.readFileSync(indexPath, "utf8");
  const scripts = [];
  html = html.replace(/\s*<script\b[^>]*\bsrc="[^"]+"[^>]*><\/script>/g, (tag) => {
    scripts.push(tag.trim());
    return "";
  });
  if (scripts.length) html = html.replace("</body>", `${scripts.join("\n")}\n</body>`);
  return html;
}

app.use("/uploads", auth, express.static(uploadsDir));
app.use(express.static(distDir, {
  index: false,
  setHeaders(res, filePath) {
    if (/\.(js|css|png|jpg|jpeg|svg|webp|woff2?)$/i.test(filePath)) {
      res.setHeader("Cache-Control", "public, max-age=2592000, immutable");
    }
  }
}));
app.use((req, res, next) => {
  if (req.path.startsWith("/api/")) return next();
  res.type("html").send(spaHtml());
});
const server = app.listen(process.env.PORT || 3001, "0.0.0.0", () => console.log(`Lead Manager API running on http://localhost:${process.env.PORT || 3001}`));
server.on("error", (error) => console.error("API server error:", error));
setInterval(() => {}, 1 << 30);
